version: "3.9"
services:
  ipfs:
     image: ipfs/go-ipfs:v0.7.0
     container_name: "ipfs"
     ports:
       - 4001:4001
       - 5001:5001
       - 8080:8080
       
    #  volumes:
    #    - ./dbdata/ipfs:/data/ipfs/

