name: Check different gateway connection methods

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        connection-method: ["default"]
        ipfs-version: ["0.8.0"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install ipfs
      run: |
        wget https://dist.ipfs.io/go-ipfs/v${{ matrix.ipfs-version }}/go-ipfs_v${{ matrix.ipfs-version }}_linux-amd64.tar.gz
        tar -xvzf go-ipfs_v${{ matrix.ipfs-version }}_linux-amd64.tar.gz
        cd go-ipfs
        sudo bash install.sh
        ipfs --version
        ipfs init --profile server
        ipfs daemon
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
